#define WHITEBOARD_POSTER_STRING_CONVERSION
#include <gusimplewhiteboard/gusimplewhiteboard.h>

#include <gusimplewhiteboardtypeClassDefs/wb_apm_interface.h>
#include <gusimplewhiteboardtypeClassDefs/wb_arrayoffilteredballobjects.h>
#include <gusimplewhiteboardtypeClassDefs/wb_arrayoffilteredsonarobjects.h>
#include <gusimplewhiteboardtypeClassDefs/wb_arrayoffilteredvisionobjects.h>
#include <gusimplewhiteboardtypeClassDefs/wb_ball.h>
#include <gusimplewhiteboardtypeClassDefs/wb_button.h>
#include <gusimplewhiteboardtypeClassDefs/wb_buttons_status.h>
#include <gusimplewhiteboardtypeClassDefs/wb_channels.h>
#include <gusimplewhiteboardtypeClassDefs/wb_clocks.h>
#include <gusimplewhiteboardtypeClassDefs/wb_count.h>
#include <gusimplewhiteboardtypeClassDefs/wb_differential_robot.h>
#include <gusimplewhiteboardtypeClassDefs/wb_fft_frequencies.h>
#include <gusimplewhiteboardtypeClassDefs/wb_filteredsonarobject.h>
#include <gusimplewhiteboardtypeClassDefs/wb_filteredvisionobject.h>
#include <gusimplewhiteboardtypeClassDefs/wb_fsm_control_status.h>
#include <gusimplewhiteboardtypeClassDefs/wb_fsm_state_status.h>
#include <gusimplewhiteboardtypeClassDefs/wb_giraff_main_serial.h>
#include <gusimplewhiteboardtypeClassDefs/wb_goal.h>
#include <gusimplewhiteboardtypeClassDefs/wb_hal_headtarget.h>
#include <gusimplewhiteboardtypeClassDefs/wb_input3d.h>
#include <gusimplewhiteboardtypeClassDefs/wb_io_pins.h>
#include <gusimplewhiteboardtypeClassDefs/wb_iot_control.h>
#include <gusimplewhiteboardtypeClassDefs/wb_kinematic_motor.h>
#include <gusimplewhiteboardtypeClassDefs/wb_lights.h>
#include <gusimplewhiteboardtypeClassDefs/wb_lines.h>
#include <gusimplewhiteboardtypeClassDefs/wb_nao_state.h>
#include <gusimplewhiteboardtypeClassDefs/wb_nxt_interface.h>
#include <gusimplewhiteboardtypeClassDefs/wb_oculus_prime_interface.h>
#include <gusimplewhiteboardtypeClassDefs/wb_oculus_prime_serial.h>
#include <gusimplewhiteboardtypeClassDefs/wb_point.h>
#include <gusimplewhiteboardtypeClassDefs/wb_point2d.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_body.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_bodysensors.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_foot.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_footsensors.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_leds.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_legjointsensors.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_legjointtemps.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_legs.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_legtemps.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_sonar.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_torso.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_torsojointsensors.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_torsojointtemps.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sensors_torsotemps.h>
#include <gusimplewhiteboardtypeClassDefs/wb_sound.h>
#include <gusimplewhiteboardtypeClassDefs/wb_switch_subsumption.h>
#include <gusimplewhiteboardtypeClassDefs/wb_switch_subsumption_traffic_lights.h>
#include <gusimplewhiteboardtypeClassDefs/wb_teleoperation.h>
#include <gusimplewhiteboardtypeClassDefs/wb_walk2014_controlstatus.h>
#include <gusimplewhiteboardtypeClassDefs/wb_walk_controlstatus.h>

#include <gusimplewhiteboard/guwhiteboardgetter.h>
#include <gusimplewhiteboard/guwhiteboardtypelist_c_generated.h>
